ConsoleWrite("InstallDate (MM/DD/YYYY HH:MM:SS): " & _GetOSInstallDate() & @CRLF)
Exit

Func _GetOSInstallDate()
    Local $wbemFlagReturnImmediately = 0x10, $wbemFlagForwardOnly = 0x20
    Local $colItems = "", $strComputer = "."

    Local $objWMIService = ObjGet("winmgmts:\\" & $strComputer & "\")
    Local $colItems = $objWMIService.ExecQuery("SELECT * FROM Win32_OperatingSystem", "WQL", _
            $wbemFlagReturnImmediately + $wbemFlagForwardOnly)

    If IsObj($colItems) Then
        For $objItem In $colItems
            Return WMIDateStringToDate($objItem.InstallDate)
        Next
    Else
        Return "No WMI Objects Found for class: Win32_OperatingSystem"
    EndIf
EndFunc   ;==>_GetOSInstallDate

Func WMIDateStringToDate($dtmDate)
    Return (StringMid($dtmDate, 5, 2) & "/" & _
            StringMid($dtmDate, 7, 2) & "/" & StringLeft($dtmDate, 4) _
             & " " & StringMid($dtmDate, 9, 2) & ":" & StringMid($dtmDate, 11, 2) & ":" & StringMid($dtmDate, 13, 2))
EndFunc   ;==>WMIDateStringToDate
